'use strict';

const P=window.SolarPhysics,$=id=>document.getElementById(id);
const canvas=$('scene'),ctx=canvas.getContext('2d'),section=$('sectionCanvas'),sctx=section.getContext('2d');
const ids=['modulesAlong','ranksUp','faces','tilt','moduleWidth','moduleLength','clampGap','alongGap','structureDrop','eastBands','westBands','modulesPerString','mpptCount','moduleVmp','moduleVoc','moduleImp','betaVoc','coldTemp','csa','cableOd','conductorTemp','epsilonR','riseTime','manualType','manualSpacing','manualLength','manualProvenance'];
const state={zoom:1,panX:0,panY:0,panning:false,lastMouse:null,selected:null,inverter:{x:-4,y:0},dragInv:false,last:null,study:null,manual:[],drawMode:false,drawStart:null};
const num=id=>Number($(id).value),fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d}):'—',set=(id,v)=>$(id).textContent=v;
const dist=(a,b)=>Math.hypot(b[0]-a[0],b[1]-a[1]);
function bands(id){const a=$(id).value.split(',').map(v=>Math.round(Number(v.trim()))).filter(v=>v>0);return a.length?a:[1];}
function input(){return{modulesAlong:Math.max(1,Math.round(num('modulesAlong'))),ranksUp:Math.max(1,Math.round(num('ranksUp'))),faces:Math.max(1,Math.min(2,Math.round(num('faces')))),tilt:num('tilt'),moduleWidth:num('moduleWidth'),moduleLength:num('moduleLength'),clampGap:num('clampGap'),alongGap:num('alongGap'),structureDrop:num('structureDrop'),eastBands:bands('eastBands'),westBands:bands('westBands'),modulesPerString:Math.max(1,Math.round(num('modulesPerString'))),mpptCount:Math.max(1,Math.round(num('mpptCount'))),moduleVmp:num('moduleVmp'),moduleVoc:num('moduleVoc'),moduleImp:num('moduleImp'),betaVoc:num('betaVoc'),coldTemp:num('coldTemp'),csa:num('csa'),cableOd:num('cableOd'),temp:num('conductorTemp'),epsilonR:num('epsilonR'),riseUs:num('riseTime')};}
function geometry(m){const t=m.tilt*Math.PI/180,rankSlope=m.moduleLength+m.clampGap,rankPlan=rankSlope*Math.cos(t),rankRise=rankSlope*Math.sin(t),modulePitch=m.moduleWidth+m.alongGap,bandLength=m.modulesAlong*modulePitch-m.alongGap,bandGap=.5,strings=[];let maxX=0;for(const d of [{face:'E',sign:-1,list:m.eastBands},{face:'W',sign:1,list:m.faces===2?m.westBands:[]}]){let x0=0;d.list.forEach((count,bi)=>{for(let r=0;r<count;r++){const y0=d.sign*r*rankPlan,y1=d.sign*(r+1)*rankPlan;strings.push({id:`${d.face}${bi+1}${String(r+1).padStart(2,'0')}`,face:d.face,sign:d.sign,band:bi,rank:r,x0,x1:x0+bandLength,y0,y1,y:(y0+y1)/2,z:(r+.5)*rankRise});}x0+=bandLength+bandGap;maxX=Math.max(maxX,x0-bandGap);});}return{strings,rankSlope,rankPlan,rankRise,modulePitch,bandLength,bandGap,width:maxX,height:2*Math.max(...m.eastBands,...m.westBands,1)*rankPlan,faceWidth:m.ranksUp*rankSlope};}
function segmentPhysics(length,spacing,m){const d=P.conductorDiameterFromArea(m.csa),tw=P.twoWire(Math.max(spacing,d*1.000001),d,m.epsilonR);return{R:P.dcResistance(length,m.csa,m.temp),L:tw.inductancePerM*length,C:tw.capacitancePerM*length,Z0:tw.z0,v:tw.velocity,delay:length/tw.velocity,d};}
function cableLengths(s,m,g){const row=m.modulesPerString*(m.moduleWidth+m.alongGap)-m.alongGap;const bandDistance=(s.band+1)*row+s.band*g.bandGap;const base=bandDistance+m.structureDrop;const offset=g.faceWidth;const positive=base+(s.face==='W'?offset:0);const negative=base+(s.face==='E'?offset:0);return{positive,negative,total:positive+negative,row,bandDistance,offset};}
function study(s,m,g){const lens=cableLengths(s,m,g),spacing=Math.max(m.cableOd,20),pPlus=segmentPhysics(lens.positive,spacing,m),pMinus=segmentPhysics(lens.negative,spacing,m),total=lens.total,R=pPlus.R+pMinus.R,L=pPlus.L+pMinus.L,C=pPlus.C+pMinus.C,delay=Math.max(pPlus.delay,pMinus.delay),rise=m.riseUs*1e-6;return{s,lens,plus:pPlus,minus:pMinus,length:total,R,L,C,delay,coldVoc:P.coldVoc(m.moduleVoc,m.modulesPerString,m.betaVoc,m.coldTemp),criterion:2*delay,margin:rise/(2*delay),distributed:rise<2*delay};}
function pairMppts(strings){return strings.map((s,i)=>Math.floor(i/2)+1);}
function bounds(g){const manual=state.manual.flatMap(x=>[x.a,x.b]);return{minX:Math.min(-8,state.inverter.x-2,...manual.map(p=>p[0]),-2),maxX:Math.max(g.width+2,...manual.map(p=>p[0]),2),minY:Math.min(-g.height/2-2,...manual.map(p=>p[1]),-2),maxY:Math.max(g.height/2+2,...manual.map(p=>p[1]),2)};}
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);ctx.setTransform(d,0,0,d,0,0);}
function transform(g){const r=canvas.getBoundingClientRect(),b=bounds(g),pad=35,fit=Math.min((r.width-2*pad)/(b.maxX-b.minX),(r.height-2*pad)/(b.maxY-b.minY)),sc=fit*state.zoom,ox=pad-b.minX*fit+state.panX,oy=r.height/2+state.panY;return{sc,ox,oy,sx:x=>ox+x*sc,sy:y=>oy+y*sc,wx:x=>(x-ox)/sc,wy:y=>(y-oy)/sc};}
function line(a,b,t,col='#000',w=2,dash=[]){ctx.save();ctx.beginPath();ctx.strokeStyle=col;ctx.lineWidth=w;ctx.setLineDash(dash);ctx.moveTo(t.sx(a[0]),t.sy(a[1]));ctx.lineTo(t.sx(b[0]),t.sy(b[1]));ctx.stroke();ctx.restore();}
function cablePath(s,g,polarity){const xTerminal=polarity==='+'?s.x1:s.x0;const yOffset=polarity==='+'?-0.05:0.05;return[[xTerminal,s.y+yOffset],[s.x0,s.y+yOffset],[state.inverter.x,state.inverter.y+(polarity==='+'?-0.18:0.18)]];}
function drawPolyline(points,t,w=3){for(let i=1;i<points.length;i++)line(points[i-1],points[i],t,'#000',w);}
function drawSection(m,g){const w=section.width,h=section.height;sctx.clearRect(0,0,w,h);const slope=m.ranksUp*g.rankSlope,run=slope*Math.cos(m.tilt*Math.PI/180),rise=slope*Math.sin(m.tilt*Math.PI/180),scale=Math.min(170/Math.max(run,1),120/Math.max(rise,1),8),cx=235,base=h-28,dx=run*scale,dy=rise*scale;sctx.strokeStyle='#263342';sctx.beginPath();sctx.moveTo(12,base);sctx.lineTo(w-12,base);sctx.stroke();sctx.lineWidth=4;sctx.strokeStyle='#27d8ff';sctx.beginPath();sctx.moveTo(cx-dx,base);sctx.lineTo(cx,base-dy);sctx.lineTo(cx+dx,base);sctx.stroke();sctx.fillStyle='#ecf5ff';sctx.font='12px sans-serif';sctx.fillText(`${fmt(m.tilt,1)}° · ${m.ranksUp} portrait ranks/face`,12,18);sctx.fillText(`Slope ${fmt(slope,3)} m · plan ${fmt(run,3)} m · rise ${fmt(rise,3)} m`,12,36);}
function draw(m,g,st){resize();const t=transform(g),r=canvas.getBoundingClientRect();state.last={m,g,t};ctx.clearRect(0,0,r.width,r.height);ctx.strokeStyle='#101a24';for(let x=0;x<=g.width;x+=10){ctx.beginPath();ctx.moveTo(t.sx(x),0);ctx.lineTo(t.sx(x),r.height);ctx.stroke();}for(const s of g.strings){const sel=st&&st.s.id===s.id,yy=Math.min(s.y0,s.y1),hh=Math.abs(s.y1-s.y0);ctx.fillStyle=sel?'#704d12':s.face==='E'?'#0f3d50':'#302653';ctx.strokeStyle=sel?'#ffb347':s.face==='E'?'#27d8ff':'#b891ff';ctx.fillRect(t.sx(s.x0),t.sy(yy),g.bandLength*t.sc,hh*t.sc);ctx.strokeRect(t.sx(s.x0),t.sy(yy),g.bandLength*t.sc,hh*t.sc);if(t.sc>8)for(let i=1;i<m.modulesAlong;i++){const x=s.x0+i*g.modulePitch;ctx.beginPath();ctx.moveTo(t.sx(x),t.sy(yy));ctx.lineTo(t.sx(x),t.sy(yy+hh));ctx.stroke();}if(t.sc>5){ctx.fillStyle='#dcecff';ctx.font='10px ui-monospace,monospace';ctx.fillText(t.sc>12?s.id:`B${s.band+1} R${s.rank+1}`,t.sx(s.x0)+3,t.sy(s.y)+3);}}
if(st){const pp=cablePath(st.s,g,'+'),pm=cablePath(st.s,g,'-');drawPolyline(pp,t,4);drawPolyline(pm,t,4);ctx.fillStyle='#fff';ctx.font='bold 15px ui-monospace,monospace';ctx.fillText(`+ ${fmt(st.lens.positive,1)} m`,t.sx(state.inverter.x)+12,t.sy(state.inverter.y-.18)-5);ctx.fillText(`− ${fmt(st.lens.negative,1)} m`,t.sx(state.inverter.x)+12,t.sy(state.inverter.y+.18)+16);}
state.manual.forEach((s,i)=>{line(s.a,s.b,t,'#27d8ff',3);const mx=(s.a[0]+s.b[0])/2,my=(s.a[1]+s.b[1])/2;ctx.fillStyle='#dff8ff';ctx.font='11px ui-monospace,monospace';ctx.fillText(`M${i+1} ${fmt(s.length,2)}m`,t.sx(mx)+4,t.sy(my)-4);});if(state.drawMode&&state.drawStart){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(t.sx(state.drawStart[0]),t.sy(state.drawStart[1]),5,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#ffb347';ctx.fillRect(t.sx(state.inverter.x)-8,t.sy(state.inverter.y)-16,16,32);ctx.fillStyle='#ffe1ad';ctx.font='11px sans-serif';ctx.fillText('INVERTER',t.sx(state.inverter.x)-28,t.sy(state.inverter.y)-22);set('zoomReadout',`${Math.round(state.zoom*100)}%`);drawSection(m,g);}
function nearest(wx,wy,g){return g.strings.find(s=>wx>=s.x0&&wx<=s.x1&&wy>=Math.min(s.y0,s.y1)&&wy<=Math.max(s.y0,s.y1))||null;}
function manualRow(seg,m,i){const p=segmentPhysics(seg.length,seg.spacing,m);return{...seg,...p,id:`M${i+1}`};}
function render(){const m=input(),g=geometry(m),mppts=pairMppts(g.strings),studies=g.strings.map(s=>study(s,m,g));if(!state.selected||!g.strings.some(s=>s.id===state.selected))state.selected=g.strings[0]?.id;const st=studies.find(x=>x.s.id===state.selected)||null;state.study=st;draw(m,g,st);set('totalStrings',String(g.strings.length));set('footprint',`${fmt(g.width,1)} × ${fmt(g.height,1)} m`);set('manualTotal',`${fmt(state.manual.reduce((a,x)=>a+x.length,0),2)} m`);if(st){set('positiveLength',`${fmt(st.lens.positive,2)} m`);set('negativeLength',`${fmt(st.lens.negative,2)} m`);set('routeLength',`${fmt(st.length,2)} m`);set('loopResistance',`${fmt(st.R,4)} Ω`);set('loopInductance',`${fmt(st.L*1e6,2)} µH`);set('delay',`${fmt(st.delay*1e6,3)} µs`);set('roundTrip',`${fmt(2*st.delay*1e6,3)} µs round trip`);set('coldVoc',`${fmt(st.coldVoc,1)} V`);$('selectedSummary').innerHTML=`<strong>${st.s.id}</strong> · ${st.s.face==='E'?'east':'west'} face · band ${st.s.band+1} · rank ${st.s.rank+1} · <strong>+ ${fmt(st.lens.positive,2)} m</strong> · <strong>− ${fmt(st.lens.negative,2)} m</strong>`;$('modelDecision').className='decision '+(st.distributed?'distributed':'');$('modelDecision').innerHTML=`<strong>${st.distributed?'DISTRIBUTED MODEL REQUIRED':'LUMPED MODEL ACCEPTABLE FOR THIS INPUT'}</strong><br>Rise time ${fmt(m.riseUs,3)} µs; 2t<sub>d</sub> ${fmt(st.criterion*1e6,3)} µs; margin ${fmt(st.margin,2)}.`;$('trace').textContent=[`STRING ${st.s.id}`,`BAND ${st.s.band+1}: ${st.s.band+1} × 30-module row distance`,`POSITIVE (+) = ${fmt(st.lens.positive,3)} m`,`NEGATIVE (−) = ${fmt(st.lens.negative,3)} m`,`TOTAL INSTALLED CONDUCTOR = ${fmt(st.length,3)} m`,`FACE OFFSET = ${fmt(st.lens.offset,3)} m; ${st.s.face==='E'?'positive is nearer to inverter':'negative is nearer to inverter'}.`,`CONDUCTOR DIAMETER = ${fmt(P.conductorDiameterFromArea(m.csa),3)} mm from metallic CSA.`,`INTERNAL LOOP INDUCTANCE = μ0/(4π) H/m at low frequency.`].join('\n');}
$('stringTable').innerHTML=studies.map((x,i)=>`<tr data-id="${x.s.id}" style="cursor:pointer;${x.s.id===state.selected?'background:#163247':''}"><td>${x.s.id}${x.s.face==='E'?' +near':' −near'}</td><td>${x.s.face}</td><td>${x.s.band+1}</td><td>${x.s.rank+1}</td><td>${fmt(x.lens.positive,2)}</td><td>${fmt(x.lens.negative,2)}</td><td>${fmt(x.length,2)}</td><td>${fmt(x.R,4)}</td><td>${fmt(x.L*1e6,2)}</td><td>${mppts[i]}</td></tr>`).join('');$('stringTable').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>{state.selected=tr.dataset.id;render();});
const rows=state.manual.map((x,i)=>manualRow(x,m,i));$('manualTable').innerHTML=rows.map(x=>`<tr><td>${x.id}</td><td>${x.type}</td><td>${fmt(x.length,3)}</td><td>${fmt(x.spacing,1)}</td><td>${fmt(x.R,5)}</td><td>${fmt(x.L*1e6,3)}</td><td>${fmt(x.C*1e9,3)}</td><td>${fmt(x.Z0,1)}</td><td>${fmt(x.delay*1e6,4)}</td><td>${x.provenance}</td></tr>`).join('');const warnings=[];if(m.modulesPerString!==m.modulesAlong)warnings.push('Modules per string differs from modules along row.');if(g.strings.length>m.mpptCount*2)warnings.push(`${g.strings.length} strings exceed ${m.mpptCount} MPPTs at two strings per MPPT.`);$('warningBox').innerHTML=warnings.map(w=>`<div class="warning">${w}</div>`).join('');}
function addManual(a,b,lengthOverride=null){const length=lengthOverride==null?dist(a,b):lengthOverride;state.manual.push({a,b,length,type:$('manualType').value,spacing:num('manualSpacing'),provenance:$('manualProvenance').value,source:lengthOverride==null?'drawn_geometry':'typed_length'});render();}
ids.forEach(id=>$(id).addEventListener('input',render));$('reset').onclick=()=>location.reload();$('drawCable').onclick=()=>{state.drawMode=!state.drawMode;state.drawStart=null;$('drawStatus').innerHTML=`Ruler: <strong>${state.drawMode?'CLICK START POINT':'READY'}</strong>`;render();};$('addTyped').onclick=()=>{const L=Math.max(0,num('manualLength'));const y=state.manual.length*.5;addManual([state.inverter.x,y],[state.inverter.x+L,y],L);};$('undoCable').onclick=()=>{state.manual.pop();render();};$('clearCables').onclick=()=>{state.manual=[];render();};$('export').onclick=()=>{const m=input(),g=geometry(m),studies=g.strings.map(s=>study(s,m,g)),manual=state.manual.map((x,i)=>manualRow(x,m,i)),payload={schema_version:'4.0.0-polarity-lengths',reliance:'Indicative topology and route-length study basis; competent-person review required.',inputs:m,inverter:state.inverter,strings:studies.map(x=>({id:x.s.id,face:x.s.face,band:x.s.band+1,rank:x.s.rank+1,positive_length_m:x.lens.positive,negative_length_m:x.lens.negative,total_conductor_m:x.length,resistance_ohm:x.R,loop_inductance_H:x.L,delay_s:x.delay,length_source:'geometry'})),manual_segments:manual};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='dc-string-polarity-study.json';a.click();};
canvas.addEventListener('wheel',e=>{e.preventDefault();state.zoom=Math.max(.25,Math.min(16,state.zoom*Math.exp(-e.deltaY*.001)));render();},{passive:false});canvas.addEventListener('mousedown',e=>{const {t,g}=state.last,wx=t.wx(e.offsetX),wy=t.wy(e.offsetY);if(state.drawMode){if(!state.drawStart){state.drawStart=[wx,wy];$('drawStatus').innerHTML='Ruler: <strong>CLICK END POINT</strong>';}else{addManual(state.drawStart,[wx,wy]);state.drawStart=null;$('drawStatus').innerHTML='Ruler: <strong>CLICK START POINT</strong>';}return;}if(Math.hypot(wx-state.inverter.x,wy-state.inverter.y)<1.5)state.dragInv=true;else{const s=nearest(wx,wy,g);if(s){state.selected=s.id;render();}else{state.panning=true;state.lastMouse={x:e.clientX,y:e.clientY};}}});window.addEventListener('mousemove',e=>{if(state.dragInv){const rect=canvas.getBoundingClientRect();state.inverter.x=state.last.t.wx(e.clientX-rect.left);state.inverter.y=state.last.t.wy(e.clientY-rect.top);render();}else if(state.panning){state.panX+=e.clientX-state.lastMouse.x;state.panY+=e.clientY-state.lastMouse.y;state.lastMouse={x:e.clientX,y:e.clientY};render();}});window.addEventListener('mouseup',()=>{state.dragInv=false;state.panning=false;});window.addEventListener('resize',render);render();