"""Solar electrical topology physics, cartridges and fleet data core."""

from .cartridges import (
    INITIAL_CARTRIDGES,
    LeapfrogCartridge,
    SequentialCartridge,
    TopologyCartridge,
    build_fleet_segments,
    validate_cross_cartridge_invariants,
    validate_segment_chains,
)
from .circuit import (
    CIRCUIT_SCHEMA_VERSION,
    CircuitModel,
    Connection,
    ConnectionKind,
    EvidenceClass,
    ObjectKind,
    PhysicalObject,
    Terminal,
    TerminalPolarity,
    canonical_circuit_json,
    canonical_circuit_payload,
)
from .circuit_validation import (
    CircuitValidationResult,
    IssueSeverity,
    ValidationIssue,
    validate_circuit_model,
    validated_circuit_hash,
)
from .fleet_store import build_deterministic_store, build_store
from .formulas import (
    cold_string_voc,
    dc_resistance,
    stored_electric_energy,
    stored_magnetic_energy,
    two_wire_parameters,
)
from .products import (
    ConductorSpec,
    EXTERNAL_STRING_6MM2,
    FACTORY_LEAD_4MM2,
)
from .segments import (
    FeasibilityResult,
    Point3D,
    SegmentRow,
    StringDefinition,
    TopologyInputs,
    archetype_strings,
    fleet_string_definitions,
    string_counts_per_inverter,
)
from .topology import (
    FormationConfig,
    GeometryConfig,
    Segment,
    StringTopology,
    build_export,
    build_site_model,
    build_string_segments,
    validate_no_user_route_lengths,
)


__all__ = [
    "INITIAL_CARTRIDGES",
    "LeapfrogCartridge",
    "SequentialCartridge",
    "TopologyCartridge",
    "build_fleet_segments",
    "validate_cross_cartridge_invariants",
    "validate_segment_chains",
    "CIRCUIT_SCHEMA_VERSION",
    "CircuitModel",
    "Connection",
    "ConnectionKind",
    "EvidenceClass",
    "ObjectKind",
    "PhysicalObject",
    "Terminal",
    "TerminalPolarity",
    "canonical_circuit_json",
    "canonical_circuit_payload",
    "CircuitValidationResult",
    "IssueSeverity",
    "ValidationIssue",
    "validate_circuit_model",
    "validated_circuit_hash",
    "build_deterministic_store",
    "build_store",
    "cold_string_voc",
    "dc_resistance",
    "stored_electric_energy",
    "stored_magnetic_energy",
    "two_wire_parameters",
    "ConductorSpec",
    "EXTERNAL_STRING_6MM2",
    "FACTORY_LEAD_4MM2",
    "FeasibilityResult",
    "Point3D",
    "SegmentRow",
    "StringDefinition",
    "TopologyInputs",
    "archetype_strings",
    "fleet_string_definitions",
    "string_counts_per_inverter",
    "FormationConfig",
    "GeometryConfig",
    "Segment",
    "StringTopology",
    "build_export",
    "build_site_model",
    "build_string_segments",
    "validate_no_user_route_lengths",
]
