(function(root,factory){'use strict';const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.V8LeapfrogModel=api;})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';
const VERSION='8.1.1',ALPHA=0.00393;
const DEFAULTS=Object.freeze({modulesPerString:30,moduleWidthM:1.303,alongRowGapM:.020,bandGapM:.500,eastBands:[5,5,2],westBands:[5,5,2],inverterDistanceM:10,scenarioDistancesM:[10,20,30],polarityConvention:'mirrored',cableR20MilliOhmPerM:3.39,cableTemperatureC:70,stringCurrentA:17.35,moduleVmpV:38.1,inverterCount:795,installedCableRatePerM:0,positiveFactoryLeadM:.350,negativeFactoryLeadM:.280,measuredLeapfrogSpanM:0,leadEvidence:'MANUFACTURER_STANDARD_NOT_AS_BUILT'});
const number=(v,f)=>Number.isFinite(Number(v))?Number(v):f;
const minimum=(v,min,f)=>Math.max(min,number(v,f));
function list(v,f){const src=Array.isArray(v)?v:String(v==null?'':v).split(','),a=src.map(x=>Number(String(x).trim())).filter(x=>Number.isFinite(x)&&x>=0);return a.length?a:f.slice();}
function bands(v,f){return list(v,f).map(x=>Math.max(0,Math.round(x))).filter(x=>x>0);}
function normalise(raw={}){return{modulesPerString:Math.max(1,Math.round(number(raw.modulesPerString,DEFAULTS.modulesPerString))),moduleWidthM:minimum(raw.moduleWidthM,.001,DEFAULTS.moduleWidthM),alongRowGapM:minimum(raw.alongRowGapM,0,DEFAULTS.alongRowGapM),bandGapM:minimum(raw.bandGapM,0,DEFAULTS.bandGapM),eastBands:bands(raw.eastBands,DEFAULTS.eastBands),westBands:bands(raw.westBands,DEFAULTS.westBands),inverterDistanceM:minimum(raw.inverterDistanceM,0,DEFAULTS.inverterDistanceM),scenarioDistancesM:list(raw.scenarioDistancesM,DEFAULTS.scenarioDistancesM),polarityConvention:raw.polarityConvention==='positive_near_both'?'positive_near_both':'mirrored',cableR20MilliOhmPerM:minimum(raw.cableR20MilliOhmPerM,0,DEFAULTS.cableR20MilliOhmPerM),cableTemperatureC:number(raw.cableTemperatureC,DEFAULTS.cableTemperatureC),stringCurrentA:minimum(raw.stringCurrentA,0,DEFAULTS.stringCurrentA),moduleVmpV:minimum(raw.moduleVmpV,.001,DEFAULTS.moduleVmpV),inverterCount:Math.max(1,Math.round(number(raw.inverterCount,DEFAULTS.inverterCount))),installedCableRatePerM:minimum(raw.installedCableRatePerM,0,DEFAULTS.installedCableRatePerM),positiveFactoryLeadM:minimum(raw.positiveFactoryLeadM,0,DEFAULTS.positiveFactoryLeadM),negativeFactoryLeadM:minimum(raw.negativeFactoryLeadM,0,DEFAULTS.negativeFactoryLeadM),measuredLeapfrogSpanM:minimum(raw.measuredLeapfrogSpanM,0,DEFAULTS.measuredLeapfrogSpanM),leadEvidence:String(raw.leadEvidence||DEFAULTS.leadEvidence)};}
function rowSpanM(m){return m.modulesPerString*m.moduleWidthM+Math.max(0,m.modulesPerString-1)*m.alongRowGapM;}
function cableResistancePerM(m){return m.cableR20MilliOhmPerM/1000*(1+ALPHA*(m.cableTemperatureC-20));}
function polarity(face,near,far,mode){return mode==='mirrored'&&face==='W'?{positiveM:far,negativeM:near}:{positiveM:near,negativeM:far};}
function buildStrings(input,distanceOverrideM){const m=normalise(input),R=rowSpanM(m),pitch=R+m.bandGapM,D=distanceOverrideM==null?m.inverterDistanceM:Math.max(0,number(distanceOverrideM,m.inverterDistanceM)),rPerM=cableResistancePerM(m),strings=[];let n=1;for(const def of [{face:'E',bands:m.eastBands},{face:'W',bands:m.westBands}])def.bands.forEach((count,bi)=>{const offset=bi*pitch,near=D+offset,far=near+R,seq=polarity(def.face,near,far,m.polarityConvention);for(let rank=1;rank<=count;rank++){const dR=R*rPerM,dV=m.stringCurrentA*dR,stringVmp=m.modulesPerString*m.moduleVmpV;strings.push({number:n,stringId:`${def.face}${bi+1}-${String(rank).padStart(2,'0')}`,positiveId:`${n}+`,negativeId:`${n}−`,face:def.face,band:bi+1,rank,bandOffsetM:offset,inverterDistanceM:D,nearRouteM:near,farRouteM:far,rowSpanM:R,basePairM:2*near,sequential:{positiveM:seq.positiveM,negativeM:seq.negativeM,totalExternalM:seq.positiveM+seq.negativeM,additionalRowReturnM:R},leapfrog:{positiveM:near,negativeM:near,totalExternalM:2*near,additionalRowReturnM:0},saving:{externalCableM:R,resistanceOhmPerString:dR,voltageDropVPerString:dV,voltageDropPercentOfStringVmp:stringVmp?100*dV/stringVmp:0,powerLossWPerString:m.stringCurrentA*m.stringCurrentA*dR,installedCostPerString:R*m.installedCableRatePerM}});n++;}});return strings;}
function leadFeasibility(input){const m=normalise(input),available=m.positiveFactoryLeadM+m.negativeFactoryLeadM;if(!(m.measuredLeapfrogSpanM>0))return{status:'UNRESOLVED',availableCombinedLeadM:available,requiredMeasuredSpanM:null,marginM:null,evidence:m.leadEvidence,message:'Enter the measured connector-to-connector leapfrog span before making a feasibility verdict.'};const margin=available-m.measuredLeapfrogSpanM;return{status:margin>=0?'PASSES_LENGTH_SCREEN':'FAILS_LENGTH_SCREEN',availableCombinedLeadM:available,requiredMeasuredSpanM:m.measuredLeapfrogSpanM,marginM:margin,evidence:m.leadEvidence,message:margin>=0?'Combined lead length exceeds the entered routed span. Bend radius, support and slack still require review.':'Combined lead length is shorter than the entered routed span.'};}
function calculate(raw={},distanceOverrideM){const input=normalise(raw),strings=buildStrings(input,distanceOverrideM),R=rowSpanM(input),rPerM=cableResistancePerM(input),totals=strings.reduce((a,s)=>{a.sequentialExternalM+=s.sequential.totalExternalM;a.leapfrogExternalM+=s.leapfrog.totalExternalM;a.externalCableSavingM+=s.saving.externalCableM;a.powerLossSavingW+=s.saving.powerLossWPerString;a.installedCostSaving+=s.saving.installedCostPerString;return a;},{sequentialExternalM:0,leapfrogExternalM:0,externalCableSavingM:0,powerLossSavingW:0,installedCostSaving:0}),x=strings[0]||null;return{modelVersion:VERSION,formulaId:'v8-1-sequential-versus-leapfrog-external-cable',input,geometry:{modulePitchM:input.moduleWidthM+input.alongRowGapM,rowSpanM:R,bandPitchM:R+input.bandGapM},electrical:{cableResistance20OhmPerM:input.cableR20MilliOhmPerM/1000,cableResistanceOperatingOhmPerM:rPerM,stringVmpV:input.modulesPerString*input.moduleVmpV,resistanceSavingOhmPerString:x?x.saving.resistanceOhmPerString:0,voltageDropSavingVPerString:x?x.saving.voltageDropVPerString:0,voltageDropSavingPercentOfStringVmp:x?x.saving.voltageDropPercentOfStringVmp:0,powerLossSavingWPerString:x?x.saving.powerLossWPerString:0},totals:{stringsPerInverter:strings.length,...totals,fleetSequentialExternalKm:totals.sequentialExternalM*input.inverterCount/1000,fleetLeapfrogExternalKm:totals.leapfrogExternalM*input.inverterCount/1000,fleetExternalCableSavingKm:totals.externalCableSavingM*input.inverterCount/1000,fleetPowerLossSavingKWAtEnteredCurrent:totals.powerLossSavingW*input.inverterCount/1000,fleetInstalledCostSaving:totals.installedCostSaving*input.inverterCount},leadFeasibility:leadFeasibility(input),strings};}
function scenarioStudies(raw={}){const input=normalise(raw);return input.scenarioDistancesM.map(distanceM=>{const s=calculate(input,distanceM);return{distanceM,stringsPerInverter:s.totals.stringsPerInverter,sequentialExternalM:s.totals.sequentialExternalM,leapfrogExternalM:s.totals.leapfrogExternalM,externalCableSavingM:s.totals.externalCableSavingM,fleetExternalCableSavingKm:s.totals.fleetExternalCableSavingKm,inverterPowerLossSavingKW:s.totals.powerLossSavingW/1000,fleetPowerLossSavingKW:s.totals.fleetPowerLossSavingKWAtEnteredCurrent};});}
const close=(a,b,t=1e-9)=>Math.abs(a-b)<=t;
function runGoldenTests(){const s=calculate(DEFAULTS),s30=calculate({...DEFAULTS,inverterDistanceM:30}),west=s.strings.find(x=>x.face==='W'),tests=[{name:'Default row span is 39.67 m',pass:close(s.geometry.rowSpanM,39.67),actual:s.geometry.rowSpanM,expected:39.67},{name:'Default topology contains 24 strings',pass:s.totals.stringsPerInverter===24,actual:s.totals.stringsPerInverter,expected:24},{name:'Saving is one row span per string',pass:s.strings.every(x=>close(x.saving.externalCableM,s.geometry.rowSpanM)),actual:s.strings[0]&&s.strings[0].saving.externalCableM,expected:s.geometry.rowSpanM},{name:'Default saving is 952.08 m per inverter',pass:close(s.totals.externalCableSavingM,952.08,1e-6),actual:s.totals.externalCableSavingM,expected:952.08},{name:'Saving is independent of inverter distance',pass:close(s.totals.externalCableSavingM,s30.totals.externalCableSavingM),actual:s30.totals.externalCableSavingM,expected:s.totals.externalCableSavingM},{name:'West sequential polarity is mirrored',pass:!!west&&west.sequential.positiveM===west.farRouteM&&west.sequential.negativeM===west.nearRouteM,actual:west?`${west.sequential.positiveM}/${west.sequential.negativeM}`:'missing',expected:west?`${west.farRouteM}/${west.nearRouteM}`:'west string'},{name:'Leapfrog places both terminals at the near route',pass:s.strings.every(x=>x.leapfrog.positiveM===x.nearRouteM&&x.leapfrog.negativeM===x.nearRouteM),actual:s.strings[0]?`${s.strings[0].leapfrog.positiveM}/${s.strings[0].leapfrog.negativeM}`:'missing',expected:s.strings[0]&&s.strings[0].nearRouteM}];return{version:VERSION,passed:tests.filter(x=>x.pass).length,total:tests.length,allPassed:tests.every(x=>x.pass),tests};}
return Object.freeze({VERSION,DEFAULTS,COPPER_ALPHA_20:ALPHA,normalise,rowSpanM,cableResistancePerM,buildStrings,calculate,scenarioStudies,leadFeasibility,runGoldenTests});
});
